name: Link Checker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    # Run automatically every Sunday at midnight
    - cron: '0 0 * * 0'

jobs:
  check-links:
    name: Check for broken links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Lychee Link Checker
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: '--accept 200,204,429 --verbose --no-progress "**/*.md"'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
